# Generated by Django 3.2.4 on 2021-06-28 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='projectMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
                ('project_title', models.CharField(max_length=100)),
                ('project_subtitle', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='projectImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_path', models.CharField(max_length=100)),
                ('image_description', models.CharField(max_length=500)),
                ('project_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.projectmaster')),
            ],
        ),
        migrations.CreateModel(
            name='projectClients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('client_url', models.CharField(max_length=200)),
                ('project_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.projectmaster')),
            ],
        ),
    ]
